name: Deploy staging to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - staging

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: staging

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      # - name: Create deployment
      #   uses: bobheadxi/deployments@v1
      #   id: deployment
      #   with:
      #     step: start
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     env: staging

      # - name: List build directory contents
      #   run: ls public
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::865021821765:role/GitHub
          role-duration-seconds: 3600 #adjust as needed for your build time
          aws-region: us-east-1

      - name: Deploy to AWS
        run: pnpm run deploy:staging

      # - name: Update deployment status
      #   uses: bobheadxi/deployments@v1
      #   if: always()
      #   with:
      #     step: finish
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     status: ${{ job.status }}
      #     env: ${{ steps.deployment.outputs.env }}
      #     deployment_id: ${{ steps.deployment.outputs.deployment_id }}
